# Generated by Django 2.1.2 on 2019-03-01 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('work', '0001_initial'), ('work', '0002_auto_20190301_1926'), ('work', '0003_auto_20190301_1927'), ('work', '0004_auto_20190301_1956'), ('work', '0005_remove_vacancy_apply_url'), ('work', '0006_auto_20190301_2045'), ('work', '0007_auto_20190301_2047')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_at', models.DateTimeField(verbose_name='Published at')),
                ('requirements', models.TextField(verbose_name='Requirements')),
                ('responsibility', models.TextField(verbose_name='Responsibilities')),
                ('subway', models.CharField(max_length=64, null=True, verbose_name='Subway')),
                ('vacancy', models.CharField(max_length=128, verbose_name='Vacancy')),
                ('has_test', models.BooleanField(null=True, verbose_name='Has Test')),
                ('employer', models.CharField(max_length=256, verbose_name='Employer')),
                ('salary_from', models.FloatField(null=True, verbose_name='Salary From')),
                ('salary_to', models.FloatField(null=True, verbose_name='Salary To')),
                ('url', models.CharField(max_length=128, null=True, verbose_name='URL')),
                ('hh_id', models.BigIntegerField(unique=True, verbose_name='HH id')),
                ('apply_url', models.CharField(max_length=128, null=True, verbose_name='Apply URL')),
                ('currency', models.CharField(default='RUR', max_length=32, null=True, verbose_name='Currency')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=64, verbose_name='Tag')),
            ],
        ),
        migrations.CreateModel(
            name='VacancyTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.Tag', verbose_name='Tag')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.Vacancy', verbose_name='Vacancy')),
            ],
        ),
    ]
