# Generated by Django 2.1.2 on 2019-03-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial_squashed_0007_auto_20190301_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='responsibility',
            field=models.TextField(null=True, verbose_name='Responsibilities'),
        ),
    ]
