# Generated by Django 2.1.2 on 2019-03-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_auto_20190301_2117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ('-published_at',)},
        ),
        migrations.AddField(
            model_name='vacancy',
            name='source',
            field=models.CharField(choices=[('hh', 'HeadHunter'), ('moi_krug', 'Мой Круг')], default='hh', max_length=32, verbose_name='Source'),
        ),
    ]
