# Generated by Django 2.1.2 on 2019-03-02 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_auto_20190302_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('vacancy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='work.Vacancy', verbose_name='Vacancy')),
            ],
        ),
    ]
